# Generated by Django 5.1.3 on 2024-11-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
