# Generated by Django 5.1.3 on 2024-11-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0002_channel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='channel',
            name='videos',
        ),
        migrations.AddField(
            model_name='channel',
            name='videos',
            field=models.IntegerField(default=0),
        ),
    ]
