# Generated by Django 5.1.3 on 2024-11-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0003_channel_views_remove_channel_videos_channel_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videoId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
