# Generated by Django 5.1.3 on 2024-12-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0004_video_videoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='founder',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='channel',
            name='story',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='channel',
            name='whoarewe',
            field=models.TextField(default=''),
        ),
    ]
