# Generated by Django 5.1.3 on 2024-12-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0006_storysubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='DMchannelsubs',
            field=models.IntegerField(default=30),
        ),
    ]
